// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBD_m_fBs-wASMzy6dGbsC5EUgl8JxW8kI',
    appId: '1:6340458131:web:7357faa5252a2f6fed7f66',
    messagingSenderId: '6340458131',
    projectId: 'flutterfirebaseeducated-1de30',
    authDomain: 'flutterfirebaseeducated-1de30.firebaseapp.com',
    storageBucket: 'flutterfirebaseeducated-1de30.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAScNij_S0e2gB8zAK-PuT-255QwekKHs8',
    appId: '1:6340458131:android:b4c5e8d93c390338ed7f66',
    messagingSenderId: '6340458131',
    projectId: 'flutterfirebaseeducated-1de30',
    storageBucket: 'flutterfirebaseeducated-1de30.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCdAk_3r8SaWc-5Lo2tob__EaigMLEPCdA',
    appId: '1:6340458131:ios:ab555b6f84d7170eed7f66',
    messagingSenderId: '6340458131',
    projectId: 'flutterfirebaseeducated-1de30',
    storageBucket: 'flutterfirebaseeducated-1de30.firebasestorage.app',
    iosBundleId: 'com.example.electricityPaymentAuth',
  );
}
